//! Property tests for deterministic bounded artifact ingestion.

use proptest::prelude::*;
use quarantine_sandbox_runtime::{IngestionPolicy, ingest_bytes};

proptest! {
    #[test]
    fn ingestion_preserves_nonempty_bytes_and_identity(
        bytes in prop::collection::vec(any::<u8>(), 1..=256),
    ) {
        let policy = IngestionPolicy {
            maximum_artifact_bytes: 256,
            maximum_artifact_name_bytes: 255,
        };
        let first = ingest_bytes("sample.bin", &bytes, &policy)
            .expect("generated bytes are within the declared policy");
        let second = ingest_bytes("sample.bin", &bytes, &policy)
            .expect("the same generated bytes remain valid");

        prop_assert_eq!(first.bytes(), bytes.as_slice());
        prop_assert_eq!(first.descriptor(), second.descriptor());
    }
}
